# ===============================
# = Kafka configurations
# ===============================
spring:
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
    template:
      default-topic: marketplace_tpic
# ===============================
# = Mongodb configurations
# ===============================ß
  data:
    mongodb:
      database: ts_payment
      host: 127.0.0.1
      port: 27017
      username: ENC(oboTTC/uJoW2UtOK5IVjbUYBhS/VlEtiWJNuxksQymw=)
      password: ENC(JUMb4EebZo4k8pRi6NUhApr9+T6kbW7E74AwwNDO6E2XLfyeQcNwhg==)
  #      authentication-database: admin
# ===============================
# = Redis Cache configurations
# ===============================
  redis:
    host: redis-16699.c8.us-east-1-3.ec2.cloud.redislabs.com
    port: 16699
    password: ENC(0Q4+zlwBNJ6KbHUBRO03lTCYGSGf2tp69n9j3XNtuvczp0DfM8xZPw==)
    username: ENC(W46UMtpzORjTn2MU9b4DIwnkQanSOMSN)
    client-name: TechralSolutionLLC-devops-db
    timeout: 600000
    database: 0
  cache:
    redis:
      time-to-live: 600000
      key-prefix: mkp_
    cache-names: Message
    type: redis
# ===============================
# = Oracle configurations       =
# ===============================ß
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${SID:ORCL}
    username: ENC(Vf861OuWGEmKT+4fnEffRwNt+Svl3xta)
    password: ENC(C9mMHAvSqD4fvnucNNvnS6s5kniaxf10jT6cNt+NNllX4Rpm3PEUrw==)
    hikari:
      pool-name: HikariPoolNotification
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
# ===============================
# = Eureka Server configurations
# ===============================ß
eureka:
  client:
    service-url :
      defaultZone:
        ${EUREKA_URI:http://127.0.0.1:5002/eureka} # add your port where your eureka server running
  instance :
    prefer-ip-address : true

    
